### PR TITLE
client_url and detailed incident key in pagerduty handler

### PR DESCRIPTION
**Pull request by verterok**
Small improvements to the pagerduty handler:
  - add extra values to the incident key (level, alert and target if available)
  - set client_url to the graphite graph url

### CODE REVIEW

**Comment by GarrettHeel** [comment]
Doesn't the `incident_key` need to be consistent between a trigger and resolve for PagerDuty to handle an incident correctly? Adding variable values like `level` seems like it would break this behaviour

**Comment by verterok** [comment]
Hi Garrett,
Thanks for the prompt reply.
You'r right about the level.
I wanted to get a more detailed incident key as it's the ID/key used by pagerduty to de-duplicate events. With the current rule['raw'] I have alerts with similar rules that might be treated as duplicate events by PD.
Would you be ok to remove level but keep alert.name and target?

**Comment by GarrettHeel** [comment]
Right, it looks like the fact that we use `rule["raw"]` as the incident_key means that tracking of an incident wont work correctly right now.

Personally I'd like to see just the alert name as the incident key. Extra details like the target should be in the message or somewhere else.

**Comment by verterok** [comment]
Just pushed the changes. 
incident_key is now alert={alert.name},rule={rule['raw']}

Thanks.

**Comment by shrijeet** [comment]
> With the current rule['raw'] I have alerts with similar rules that might be treated as duplicate events by PD.

This is a serious issue. @garrettheel thoughts? The change looks ready to be merged.

**Comment by garrettheel** [comment]
LGTM. Thanks for fixing!

**Pull request merged**
